version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/notices_board
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=221001
    extra_hosts:
      - "host.docker.internal:host-gateway"